packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  esbuild: false
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - shadcn@4.9.0
